### PR TITLE
Replace broken character with colon character

### PR DESCRIPTION
**Pull request by agilob**
I currently see the page with:

image

### CODE REVIEW

**Comment by YangKeao** [comment]
I failed to reproduce this problem on my local machine (Firefox 90.0.2, and the font matches `Noto Sans CJK SC`).

**Comment by agilob** [comment]
The char you currently have there is U+FF1A (some kind of full width colon) while basic colon is U+003A. besides, do you expect all doc readers to install `Noto Sans CJK SC`?

**Comment by cwen0** [comment]
@agilob Can you fix [DCO](https://github.com/chaos-mesh/website/pull/112/checks?check_run_id=3223022723)? Thanks!

**Comment by agilob** [comment]
Fkxed

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
