### PR TITLE
Typo in helm chart repo link fix

### PR DESCRIPTION
**Pull request by MA3CIN**
I believe i found a typo in the documentation when i was working on my own project
Let me know if i'm wrong - i will delete the PR

### CODE REVIEW

**Comment by MA3CIN** [comment]
image

**Comment by STRRL** [comment]
Thanks for your contribution!  :heart: 

I noticed that DCO check failed, please click "Details" to see how to fix it. :heart:

**Comment by en-jin19** [comment]
Hi @MA3CIN, could you please fix the DCO error? thanks!

**Comment by g1eny0ung** [comment]
> I believe i found a typo in the documentation when i was working on my own project Let me know if i'm wrong - i will delete the PR

True dat. I will help you to fix the DCO check and merge this PR soon. Thx for your contribution. ❤️

**Pull request merged**
