### PR TITLE
docs: add VMName property to AzureChaos documentation

### PR DESCRIPTION
**Pull request by dstoecklein**
Its missing in the documentation but a required property to run the experiment.

### CODE REVIEW

**Comment by dstoecklein** [comment]
@g1eny0ung anything I can do to pass the markdown check?

**Comment by g1eny0ung** [comment]
@dstoecklein Thanks for adding it! You can safely ignore the markdown links check due to the GitHub CI environment may have blocked some popular sites, like Twitter. 🫤

**Pull request merged**
