### PR TITLE
docs: fix helloworldchaos tutorial

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

The code generation part of the tutorial is incorrect because of https://github.com/chaos-mesh/chaos-mesh/pull/2353

### CODE REVIEW

**Comment by YangKeao** [comment]
@iguoyr PTAL

**Review by en-jin19 — APPROVED** [review]
LGTM

**Review by iguoyr — APPROVED** [review]
LGTM!

**Pull request merged**
