### PR TITLE
docs: add simulate-network-chaos-on-kubernetes.md

### PR DESCRIPTION
**Pull request by Liuxiaozhen12**
Signed-off-by: Xiaozhen Liu <liuxiaozhen@pingcap.com>
This PR is translated from https://github.com/chaos-mesh/website-zh/pull/31, https://github.com/chaos-mesh/website-zh/pull/42, and https://github.com/chaos-mesh/website-zh/pull/55.

### CODE REVIEW

**Comment by Liuxiaozhen12** [comment]
@YangKeao

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
