### PR TITLE
update offline installation

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>

### CODE REVIEW

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Comment by iguoyr** [comment]
https://github.com/chaos-mesh/website/blob/0a6210bcb74aab57d440370bbfbbed7d78f775e9/i18n/zh/docusaurus-plugin-content-docs/version-2.1.0/offline-installation.md#L61 

https://github.com/chaos-mesh/website/blob/0a6210bcb74aab57d440370bbfbbed7d78f775e9/docs/offline-installation.md#L63

I think we should download the correct version package here, instead of `master.zip`. The default value of image version in the master branch is `latest`, which is not wanted.

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by g1eny0ung** [comment]
> https://github.com/chaos-mesh/website/blob/0a6210bcb74aab57d440370bbfbbed7d78f775e9/i18n/zh/docusaurus-plugin-content-docs/version-2.1.0/offline-installation.md#L61
> 
> https://github.com/chaos-mesh/website/blob/0a6210bcb74aab57d440370bbfbbed7d78f775e9/docs/offline-installation.md#L63
> 
> I think we should download the correct version package here, instead of `master.zip`. The default value of image version in the master branch is `latest`, which is not wanted.

@iguoyr +1, I will open a PR to fix this.

**Pull request merged**
