### PR TITLE
Keep the chart name consistent with the previous'

### PR DESCRIPTION
**Pull request by radupopa2010**
If you install the helm chart with 
`helm install chaos-mesh chaos-mesh/chaos-mesh --namespace=chaos-testing`
 then the same chart name should be used for the upgrade

### CODE REVIEW

**Comment by radupopa2010** [comment]
@g1eny0ung Can you please review this change?

**Comment by g1eny0ung** [comment]
@radupopa2010 Seems it's also needed to update the same position in version `1.0` and `1.0.1`.

**Review by g1eny0ung — APPROVED** [review]
LGTM! Thx for helping us improve the documentation. 😄

**Comment by radupopa2010** [comment]
> LGTM! Thx for helping us improve the documentation.

Thanks for chosmesh

**Pull request merged**
