### PR TITLE
Remove "?"

### PR DESCRIPTION
**Pull request by CaitinChen**
"How to XXX" is not a question, so we must remove the question mark. We already deleted "?" in the blog post on the PingCAP website.

### CODE REVIEW

**Comment by g1eny0ung** [comment]
@CaitinChen Needs to fix the DCO. Run the following command in the local terminal can fix it:

`git commit --amend -s` and `git push -f`.

**Comment by CaitinChen** [comment]
@g1eny0ung Thanks. I'll fix the issue soon.

**Comment by CaitinChen** [comment]
@dcalvin PTAL

**Review by dcalvin — APPROVED** [review]
LGTM

**Pull request merged**
