### PR TITLE
fix(httpchaos): example value of patch body

### PR DESCRIPTION
**Pull request by Hexilee**
Signed-off-by: xixi <i@hexilee.me>

### CODE REVIEW

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Comment by g1eny0ung** [comment]
@Hexilee Also needs to sync to version 2.1.0.

**Comment by Hexilee** [comment]
> @Hexilee Also needs to sync to version 2.1.0.

Synced

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Pull request merged**
