### PR TITLE
Update configure-development-environment.md

### PR DESCRIPTION
**Pull request by mingleiw**
`make ensure-all` doesn't exist in the **Makefile** anymore, but the guide is still referencing it. Submitting this pr to update it. Please review it. Thanks!

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @mingleiw ! Thanks for your contribution.

I think we could remove the whole of step 2, because we provide docker images `ghcr.io/chaos-mesh/build-env` and `ghcr.io/chaos-mesh/dev-env`, including all the required code generation tools and code linters. So docker is the only required tool. 

How do you think about it? @YangKeao  @iguoyr

**Comment by mingleiw** [comment]
@STRRL make sense to me. I've remove the step 2 and updated the PR.

**Comment by mingleiw** [comment]
signed off all the commits

**Comment by mingleiw** [comment]
@STRRL can I get approval please? Thank you!

**Review by hfxsd — APPROVED** [review]
LGTM

**Comment by mingleiw** [comment]
@hfxsd Thanks for the review! How many LGTMs do I need to get before merge?

**Review by dcalvin — APPROVED** [review]
LGTM

**Review by STRRL — COMMENTED** [review]
LGTM!

**Review by STRRL — APPROVED** [review]

**Pull request merged**
