### PR TITLE
Clarify the usage of replace.body

### PR DESCRIPTION
**Pull request by xlgao-zju**
Signed-off-by: Xianglin Gao <xianglingao@tencent.com>

### CODE REVIEW

**Review by Oreoxmt — COMMENTED** [review]
Rest LGTM

**Comment by Oreoxmt** [comment]
@xlgao-zju Could you please fix the DCO error?

**Comment by xlgao-zju** [comment]
@Oreoxmt updated

**Comment by Oreoxmt** [comment]
@xlgao-zju If your changes apply to Chaos Mesh v2.2.0, please add the note to [`versioned_docs/version-2.2.0/simulate-http-chaos-on-kubernetes.md`](https://github.com/chaos-mesh/website/blob/3e60a1699c02dca36fbf90e7b5f05ec0f7eefdbf/versioned_docs/version-2.2.0/simulate-http-chaos-on-kubernetes.md) and [`i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/simulate-http-chaos-on-kubernetes.md`](https://github.com/chaos-mesh/website/blob/3e60a1699c02dca36fbf90e7b5f05ec0f7eefdbf/i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/simulate-http-chaos-on-kubernetes.md) files. Thanks!

**Comment by xlgao-zju** [comment]
> @xlgao-zju If your changes apply to Chaos Mesh v2.2.0, please add the note to [versioned_docs/version-2.2.0/simulate-http-chaos-on-kubernetes.md](https://github.com/chaos-mesh/website/blob/3e60a1699c02dca36fbf90e7b5f05ec0f7eefdbf/versioned_docs/version-2.2.0/simulate-http-chaos-on-kubernetes.md) and [i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/simulate-http-chaos-on-kubernetes.md](https://github.com/chaos-mesh/website/blob/3e60a1699c02dca36fbf90e7b5f05ec0f7eefdbf/i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/simulate-http-chaos-on-kubernetes.md) files. Thanks!

@Oreoxmt updated

**Review by Oreoxmt — APPROVED** [review]
LGTM

**Pull request merged**
