### PR TITLE
add documents for blockchaos in latest and 2.3.0

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### CODE REVIEW

**Comment by Oreoxmt** [comment]
@YangKeao Could you please invite a tech review? Thanks

**Comment by cwen0** [comment]
@YangKeao PTAL

**Review by STRRL — APPROVED** [review]

**Review by STRRL — APPROVED** [review]

**Review by Oreoxmt — APPROVED** [review]
LGTM

**Pull request merged**
