### PR TITLE
refine user guide and get started

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
Signed-off-by: xiang <xiang13225080@163.com>

1. move `installation` and `run_chaos_experiment` from `get_started` to `user_guide`
2. add the link of `run_chaos_experiment` in `get_started_on_kind` and `get_started_on_minikube`

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
@dcalvin @cwen0 PTAL

**Comment by WangXiangUSTC** [comment]
@g1eny0ung PTAL

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Review by dcalvin — APPROVED** [review]
LGTM

**Pull request merged**
