### PR TITLE
Fix ContianerRecordDecoder typo

### PR DESCRIPTION
**Pull request by mingleiw**
This is part of https://github.com/chaos-mesh/chaos-mesh/pull/2538. After the fix, we need to update the doc as well.

### CODE REVIEW

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by STRRL — COMMENTED** [review]
LGTM! Thanks for your contribution!

**Review by STRRL — APPROVED** [review]

**Comment by mingleiw** [comment]
@STRRL it seems like this pr can't be merged because of the do-not-merge/blocked-paths label

**Comment by STRRL** [comment]
> @STRRL it seems like this pr can't be merged because of the do-not-merge/blocked-paths label

oops let me take a look

**Pull request merged**
