### PR TITLE
zh document: update dns example for chaosd

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
Signed-off-by: xiang <xiang13225080@163.com>

### CODE REVIEW

**Comment by Oreoxmt** [comment]
@WangXiangUSTC `/i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/simulate-network-chaos-in-physical-nodes.md` 也需要相同的修改。Rest LGTM

**Comment by WangXiangUSTC** [comment]
@Oreoxmt Done, PTAL again

**Review by Oreoxmt — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
