### PR TITLE
Fix typo in workflow documentation

### PR DESCRIPTION
**Pull request by gushev**
Fix of a typo in the workflow documentation.

### CODE REVIEW

**Review by Oreoxmt — APPROVED** [review]
LGTM

**Comment by gushev** [comment]
@Oreoxmt @g1eny0ung there seem to be some dead links that are not caused by this PR, but the [markdown-link-check](https://github.com/chaos-mesh/website/runs/8166065629?check_suite_focus=true) is failing.

**Comment by g1eny0ung** [comment]
> @Oreoxmt @g1eny0ung there seem to be some dead links that are not caused by this PR, but the [markdown-link-check](https://github.com/chaos-mesh/website/runs/8166065629?check_suite_focus=true) is failing.

This check isn't required, so it can be ignored.

**Review by g1eny0ung — APPROVED** [review]
LGTM. Thanks for checking. 😃

**Pull request merged**
