### PR TITLE
Fix misspelling of chaosd

### PR DESCRIPTION
**Pull request by liys87x**
Fix chaosd startup parameter error

### CODE REVIEW

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Comment by Andrewmatilde** [comment]
Thanks for your contribution!!!!

**Comment by Andrewmatilde** [comment]
Would you like to fix it in Chinese Doc [here](i18n/zh/docusaurus-plugin-content-docs/current/simulate-physical-machine-chaos.md)?

**Comment by Andrewmatilde** [comment]
@liys87x  Would you like to fix it in Chinese Doc [here](https://github.com/chaos-mesh/website/pull/i18n/zh/docusaurus-plugin-content-docs/current/simulate-physical-machine-chaos.md)?

**Review by Andrewmatilde — APPROVED** [review]
LGTM @cwen0 PTAL

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by Oreoxmt — APPROVED** [review]
LGTM

**Pull request merged**
