### PR TITLE
docs: bypass validation for lower version of kubernetes

### PR DESCRIPTION
**Pull request by YangKeao**
https://github.com/chaos-mesh/chaos-mesh/pull/1236 , we need to bypass the validation of kubernetes to add a field `preserveUnknownFields` on lower versions of kubernetes.

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

### CODE REVIEW

**Comment by g1eny0ung** [comment]
Is this needed to apply to `v0.9.1` and `v1.0.x`?

**Comment by YangKeao** [comment]
@g1eny0ung No. I will not cherry-pick https://github.com/chaos-mesh/chaos-mesh/pull/1236 to 1.0 or lower version.

**Comment by YangKeao** [comment]
> Is this needed to apply to `v0.9.1` and `v1.0.x`?

No. I will not cherry-pick it to 1.0 and lower version.

**Comment by g1eny0ung** [comment]
> > Is this needed to apply to `v0.9.1` and `v1.0.x`?
> 
> No. I will not cherry-pick it to 1.0 and lower version.

Know about it. I will merge this PR now.

**Review by g1eny0ung — APPROVED** [review]

**Pull request merged**
