### PR TITLE
add an annotation about client/HTTPS supports for docs of HTTPChaos

### PR DESCRIPTION
**Pull request by Hexilee**
Signed-off-by: hexilee <i@hexilee.me>

### CODE REVIEW

**Comment by Hexilee** [comment]
In zh: [https://github.com/chaos-mesh/website-zh/pull/69](https://github.com/chaos-mesh/website-zh/pull/69)

**Comment by en-jin19** [comment]
@Hexilee could you please add a technical reviewer and the link of Chinese corresponding PR? thanks!

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Review by en-jin19 — APPROVED** [review]
LGTM

**Pull request merged**
