### PR TITLE
the default value of startingDeadlineSeconds is not 0, is nil

### PR DESCRIPTION
**Pull request by Oreoxmt**
Signed-off-by: Aolin <aolin.zhang@pingcap.com>
Close https://github.com/chaos-mesh/website/issues/336

### CODE REVIEW

**Comment by Oreoxmt** [comment]
@STRRL PTAL

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Comment by Oreoxmt** [comment]
@STRRL PTAL

**Pull request merged**
