### PR TITLE
Update the description of MemoryStrossors size in simulate-heavy-stress-on-kubernetes.md

### PR DESCRIPTION
**Pull request by FingerLeader**
Signed-off-by: FingerLeader <wanxfinger@gmail.com>

### CODE REVIEW

**Comment by FingerLeader** [comment]
PTAL
/cc @xlgao-zju @STRRL

**Comment by FingerLeader** [comment]
Yep, this update has been mergerd before this [PR](https://github.com/chaos-mesh/website/blob/d34719db4ae00a880d88f2a9735f4e9f0f1eccff/docs/simulate-heavy-stress-on-kubernetes.md?plain=1#L88)

**Comment by xlgao-zju** [comment]
> Yep, this update has been mergerd before this [PR](https://github.com/chaos-mesh/website/blob/d34719db4ae00a880d88f2a9735f4e9f0f1eccff/docs/simulate-heavy-stress-on-kubernetes.md?plain=1#L88)

that's cool. and I think we need also modify this description both in dashboard and maybe somewhere in the source code...

image

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
> 

@FingerLeader PTAL

**Comment by cwen0** [comment]
> > Yep, this update has been mergerd before this [PR](https://github.com/chaos-mesh/website/blob/d34719db4ae00a880d88f2a9735f4e9f0f1eccff/docs/simulate-heavy-stress-on-kubernetes.md?plain=1#L88)
> 
> that's cool. and I think we need also modify this description both in dashboard and maybe somewhere in the source code...
> 
> image

@FingerLeader Can you help to fix it?

**Review by en-jin19 — APPROVED** [review]
LGTM

**Comment by FingerLeader** [comment]
> > > Yep, this update has been mergerd before this [PR](https://github.com/chaos-mesh/website/blob/d34719db4ae00a880d88f2a9735f4e9f0f1eccff/docs/simulate-heavy-stress-on-kubernetes.md?plain=1#L88)
> > 
> > 
> > that's cool. and I think we need also modify this description both in dashboard and maybe somewhere in the source code...
> > image
> 
> @FingerLeader Can you help to fix it?

Got it

**Pull request merged**
