### PR TITLE
typos

### PR DESCRIPTION
**Pull request by KasperKornak**
Signed-off-by: KasperKornak <kasper.kornak@gmail.com>

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @KasperKornak, could you fix the DCO?

**Comment by KasperKornak** [comment]
> Hi @KasperKornak, could you fix the DCO?

Hi, I'm new to this type of things :D, could you help me with solving this issue?

**Comment by STRRL** [comment]
> > Hi @KasperKornak, could you fix the DCO?
> 
> Hi, I'm new to this type of things :D, could you help me with solving this issue?

It requires you to rebase the current branch with the "sign off".

You could take a look on: https://github.com/chaos-mesh/website/pull/335/checks?check_run_id=7725615169

**Review by Oreoxmt — APPROVED** [review]
LGTM

**Comment by Oreoxmt** [comment]
@STRRL PTAL

**Review by STRRL — APPROVED** [review]

**Pull request merged**
