### PR TITLE
reUpdate description of memory stressors

### PR DESCRIPTION
**Pull request by FingerLeader**
Signed-off-by: FingerLeader <wanxfinger@gmail.com>
 
It was updated in PR #288 , but this update was wrongly overwritten by PR #267 .

### CODE REVIEW

**Review by Oreoxmt — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@FingerLeader Can you fix the conflicts?

**Comment by FingerLeader** [comment]
> @FingerLeader Can you fix the conflicts?

Fixed!

**Pull request merged**
