### PR TITLE
docs: add simulate disk faults.md

### PR DESCRIPTION
**Pull request by Liuxiaozhen12**
Signed-off-by: Liuxiaozhen12 <82579298+Liuxiaozhen12@users.noreply.github.com>
This PR is translated from https://github.com/chaos-mesh/website-zh/pull/16 and https://github.com/chaos-mesh/website-zh/pull/43.

### CODE REVIEW

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Comment by Liuxiaozhen12** [comment]
This PR is ready to merge.

**Pull request merged**
