### PR TITLE
fix: should be CPU instead of memory

### PR DESCRIPTION
**Pull request by etigerstudio**

### CODE REVIEW

**Review by g1eny0ung — APPROVED** [review]
LGTM. Thx for the correction!

**Comment by g1eny0ung** [comment]
@etigerstudio An additional step is needed to merge this PR, the DCO check failed.

You can fix it by:

```shell
git commit --amend --signoff
git push --force
```

**Comment by etigerstudio** [comment]
> @etigerstudio An additional step is needed to merge this PR, the DCO check failed.
> 
> You can fix it by:
> 
> ```shell
> git commit --amend --signoff
> git push --force
> ```

done

**Pull request merged**
