### PR TITLE
fix: correct IOChaos containerNames

### PR DESCRIPTION
**Pull request by inetkiller**
General fields ContainerName should be containerNames, and type is  []string

### CODE REVIEW

**Comment by Oreoxmt** [comment]
@inetkiller Thanks for your contribution! Please fix the DCO.

You can fix it by:

```
git commit --amend --signoff
git push --force
```

**Comment by Oreoxmt** [comment]
@STRRL PTAL

**Comment by inetkiller** [comment]
> 

done

**Review by g1eny0ung — APPROVED** [review]
@inetkiller LGTM. Thank you for your correction!

**Pull request merged**
