### PR TITLE
Update verify-installation.md

### PR DESCRIPTION
**Pull request by sevenleave**
`kubectl get po -n chaos-mesh`修改为`kubectl get po -n chaos-testing`

### CODE REVIEW

**Comment by Oreoxmt** [comment]
@STRRL PTAL

**Comment by STRRL** [comment]
Hi @sevenleave, thanks for your contribution!

I realize that there is a mess about the usage between `chaos-mesh` and `chaos-testing` for the namespace. And we prefer to use `chao-mesh`, not `chaos-testing`.

So these changes (`chaos-mesh` -> `chaos-testing`) would not be merged, and could you help us to modify them in other places?

**Comment by STRRL** [comment]
BTW, please fix the DCO check: https://github.com/chaos-mesh/website/pull/353/checks?check_run_id=8466962998

**Comment by g1eny0ung** [comment]
Close due to #361.

**Pull request closed without merging**
