### PR TITLE
docs: fix incorrection example

### LINKED ISSUE #192: Wrong documentation in create-chaos-mesh-workflow
- missing `type` for schedule in https://github.com/chaos-mesh/website/blob/a87bcb6ca2a69549efe90b6c51090df5768c8dca/docs/create-chaos-mesh-workflow.md?plain=1#L75-L82
- should be an English dot: https://github.com/chaos-mesh/website/blob/a87bcb6ca2a69549efe90b6c51090df5768c8dca/docs/create-chaos-mesh-workflow.md?plain=1#L95

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

close #192

### CODE REVIEW

**Comment by STRRL** [comment]
And it seems husky re-format my content, bring some unnecessary changes.

Should I keep these changes or diable husky? How to disable husky on my local machine if I have to do? @g1eny0ung

**Comment by g1eny0ung** [comment]
> And it seems husky re-format my content, bring some unnecessary changes.
> 
> Should I keep these changes or diable husky? How to disable husky on my local machine if I have to do? @g1eny0ung

All the automatic modifications can be retained. If want to ignore `husky`, you can refer to https://typicode.github.io/husky/#/?id=with-env-variables or use `git commit --no-verify`.

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@STRRL Please fix the conflicts! Thanks!

**Review by en-jin19 — APPROVED** [review]
LGTM

**Pull request merged**
