### PR TITLE
New Docs: Uninstallation

### LINKED ISSUE #147: New docs request: Uninstall and reinstall Chaos Mesh
as mentioned in this comments: https://github.com/chaos-mesh/chaos-mesh/issues/2100#issuecomment-901099621, there are nearly NO documents about how to uninstall and reinstall chaos mesh.

### PR DESCRIPTION
**Pull request by STRRL**
close #147

### CODE REVIEW

**Review by g1eny0ung — APPROVED** [review]
LGTM. And before merging this PR, it's needed to copy these docs to `v2.1.x` docs.

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@STRRL We also need to add this doc to v2.1.1 version

**Comment by STRRL** [comment]
> @STRRL We also need to add this doc to v2.1.1 version

Updated in https://github.com/chaos-mesh/website/pull/197;

**Pull request merged**
