### PR TITLE
update images for offline installation

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

Update image name used by offline installation.

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL

/cc @Andrewmatilde

**Review by en-jin19 — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@STRRL DCO checker was broken.

**Pull request merged**
