### PR TITLE
Update simulate-heavy-stress-on-kubernetes.md

### PR DESCRIPTION
**Pull request by xlgao-zju**

### CODE REVIEW

**Comment by xlgao-zju** [comment]
cc @FingerLeader

**Comment by FingerLeader** [comment]
Could you please update the same English docs of v2.1.4 and v2.0.7 and Chinese docs of v2.0.7?

**Comment by xlgao-zju** [comment]
> Could you please update the same English docs of v2.1.4 and v2.0.7 and Chinese docs of v2.0.7?

Updated, PTAL

**Review by FingerLeader — APPROVED** [review]
LGTM!

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by en-jin19 — APPROVED** [review]
LGTM

**Pull request merged**
