### PR TITLE
chore: update supported versions

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

It's a part of https://github.com/chaos-mesh/chaos-mesh/issues/2719

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL

/cc @g1eny0ung @cwen0 @YangKeao @en-jin19

**Review by en-jin19 — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Pull request merged**
