### PR TITLE
docs: update testing coverage,

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

close https://github.com/chaos-mesh/chaos-mesh/issues/3086

This PR is the last step for migrating e2e test from Jenkins to GitHub Actions

Changes:

- remove description for unmaintained branches
- update testing coverage with the latest e2e tests

https://github.com/chaos-mesh/chaos-mesh/blob/master/.github/workflows/e2e_test.yml#L53-L56

### CODE REVIEW

**Review by en-jin19 — APPROVED** [review]
LGTM

**Comment by en-jin19** [comment]
@STRRL Could you please invite a tech reviewer? thank you!

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
