### PR TITLE
repo from "helm/chaos-mesh" to "chaos-mesh/chaos-mesh"

### PR DESCRIPTION
**Pull request by erekgit**
incorrect helm repo being specified.   needs to be "chaos-mesh/chaos-mesh"

### CODE REVIEW

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Comment by erekgit** [comment]
> LGTM

@g1eny0ung Should these other locations be updated as well?

https://github.com/chaos-mesh/chaos-mesh/search?q=helm%2Fchaos-mesh

**Comment by g1eny0ung** [comment]
@erekgit Not needed. This is for those who want to install the latest version or related to buildingscripts.

**Comment by g1eny0ung** [comment]
@erekgit Not needed. This is for those who want to install the latest version or related to building scripts.

**Comment by g1eny0ung** [comment]
`helm/chaos-mesh` is the repo path https://github.com/chaos-mesh/chaos-mesh/tree/master/helm/chaos-mesh.

**Comment by g1eny0ung** [comment]
@erekgit Not needed. `helm/chaos-mesh` represents the subpath https://github.com/chaos-mesh/chaos-mesh/tree/master/helm/chaos-mesh. This is use for those who want to use the latest version, or related to the building scripts.

**Comment by g1eny0ung** [comment]
@erekgit Not needed. `helm/chaos-mesh` represents the subpath https://github.com/chaos-mesh/chaos-mesh/tree/master/helm/chaos-mesh. This is used for those who want to use the latest version. Or related to the building scripts.

**Pull request merged**
